### ISSUE TITLE
nebula importer error: authentication fails, Invalid data length

### ISSUE THREAD

**Issue by sunkararp** [wey-gu/nebula-shareholding-example#2]
- We are getting 'authentication fails, Invalid data length' error 
- We followed this documentation https://docs.nebula-graph.io/2.6.1/nebula-importer/use-importer/
- Here is the screen capture
![image](https://user-images.githubusercontent.com/10903166/148487846-92080140-5bbb-4901-beb6-c3d0731eb04f.png)

**Comment by sunkararp** [comment]
vesoft/nebula-importer:v2.6.0 docker image works fine

**Comment by whisperbb** [comment]
hello, how did you solve it?

**Comment by wey-gu** [comment]
@sunkararp sorry I missed your issue.
@whisperbb looks like this issue was caused by mismatching of the importer(in master) and nebula-graph(in 2.6.x)
Please ensure the importer and nebula graph are in the same version(i.e. should all be in like 2.6.x)
